sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.2
  - ruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: 2.0.0
    - rvm: ruby-head
    - rvm: rbx-2
services:
  - redis-server
script: bin/rspec
bundler_args: --without benchmarking
